// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llajnhiccmvkvphpzdrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYWpuaGljY212a3ZwaHB6ZHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NDM2MzgsImV4cCI6MjA5MTAxOTYzOH0.8WxGXwszX7mKC6HkhIKruP1qirKZMneydjReXw9N--c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});